# Travis-CI Build for Glimpse.ElasticSearch
# see travis-ci.org for details

language: csharp
solution: Glimpse.ElasticSearch.sln

# Make sure build dependencies are installed.
install:
  - nuget restore Glimpse.ElasticSearch.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner

# Run the build script
script:
  - xbuild /p:Configuration=Release Glimpse.ElasticSearch.sln
  - mono ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe ./Glimpse.Elasticsearch.Tests/bin/Release/Glimpse.Elasticsearch.Tests.dll
  
# Only watch the master branch.
branches:
 only:
   - master
   - dev
 